#! /bin/bash

dwmblocks &
feh --bg-max --randomize ~/Pictures/wallpapers/* &
nm-applet &
volumeicon &
picom --config $HOME/.xmonad/scripts/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

exec dwm


